"""Fish completion script generator for wArgs.

Generates fish completion scripts that can be placed in
~/.config/fish/completions/ or /usr/share/fish/completions/.
"""

from __future__ import annotations

from textwrap import dedent
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from wargs.completion.generator import CompletionOption, CompletionSpec


def generate_fish_completion(spec: CompletionSpec) -> str:
    """Generate a Fish completion script from a CompletionSpec.

    Args:
        spec: The completion specification.

    Returns:
        Fish completion script as a string.
    """
    prog = spec.prog

    script_parts = [
        f"# Fish completion script for {prog}",
        "# Generated by wArgs",
        "",
        "# Disable file completion by default",
        f"complete -c {prog} -f",
        "",
    ]

    # Add global options
    for opt in spec.global_options:
        completions = _build_fish_option_completions(prog, opt)
        script_parts.extend(completions)

    # Add subcommands
    if spec.subcommands:
        script_parts.append("")
        script_parts.append("# Subcommands")

        # Define condition for no subcommand yet
        subcmd_names = [sub.name for sub in spec.subcommands]
        no_subcmd_cond = f"not __fish_seen_subcommand_from {' '.join(subcmd_names)}"

        for sub in spec.subcommands:
            desc = sub.description.replace("'", "\\'").replace("\n", " ")[:50]
            script_parts.append(
                f"complete -c {prog} -n '{no_subcmd_cond}' -a '{sub.name}' -d '{desc}'"
            )

        # Add subcommand-specific options
        for sub in spec.subcommands:
            script_parts.append("")
            script_parts.append(f"# Options for {sub.name}")
            subcmd_cond = f"__fish_seen_subcommand_from {sub.name}"

            for opt in sub.options:
                completions = _build_fish_option_completions(
                    prog, opt, condition=subcmd_cond
                )
                script_parts.extend(completions)

    script_parts.append("")

    return "\n".join(script_parts)


def _build_fish_option_completions(
    prog: str, opt: CompletionOption, condition: str | None = None
) -> list[str]:
    """Build fish completion commands for an option.

    Args:
        prog: Program name.
        opt: CompletionOption instance.
        condition: Optional condition for when to show this completion.

    Returns:
        List of fish complete commands.
    """
    completions: list[str] = []

    if not opt.flags:
        return completions

    # Build base command
    parts = [f"complete -c {prog}"]

    if condition:
        parts.append(f"-n '{condition}'")

    # Add flags
    for flag in opt.flags:
        if flag.startswith("--"):
            parts.append(f"-l '{flag[2:]}'")
        elif flag.startswith("-") and len(flag) == 2:
            parts.append(f"-s '{flag[1]}'")

    # Add description
    desc = opt.description.replace("'", "\\'").replace("\n", " ")[:60]
    if desc:
        parts.append(f"-d '{desc}'")

    # Handle value completion
    if opt.takes_value:
        if opt.choices:
            parts.append("-x")  # Exclusive (no file completion)
            parts.append(f"-a '{' '.join(opt.choices)}'")
        elif opt.file_completion:
            parts.append("-F")  # Force file completion
        elif opt.directory_completion:
            parts.append("-a '(__fish_complete_directories)'")
        else:
            parts.append("-x")  # Requires argument
    else:
        # Boolean flag - no argument
        pass

    completions.append(" ".join(parts))

    return completions


def get_fish_completion_install_instructions(prog: str) -> str:
    """Get installation instructions for Fish completion.

    Args:
        prog: The program name.

    Returns:
        Human-readable installation instructions.
    """
    return dedent(f"""\
        # To enable {prog} fish completion, choose one of:

        # Option 1: Save to your user completions directory
        {prog} --completion fish > ~/.config/fish/completions/{prog}.fish

        # Option 2: System-wide installation
        {prog} --completion fish > /usr/share/fish/completions/{prog}.fish

        # Option 3: Evaluate directly (add to ~/.config/fish/config.fish)
        {prog} --completion fish | source
    """)


__all__ = [
    "generate_fish_completion",
    "get_fish_completion_install_instructions",
]
